jupyterhub:
  ingress:
    hosts:
      - aup.pilot.2i2c.cloud
    tls:
      - secretName: https-auto-tls
        hosts:
          - aup.pilot.2i2c.cloud
  custom:
    2i2c:
      add_staff_user_ids_to_admin_users: true
      add_staff_user_ids_of_type: "github"
    homepage:
      templateVars:
        org:
          name: The American University of Paris
          logo_url: https://www.aup.edu/sites/default/files/images/widget-assets/image/auplogo.jpeg
          url: https://www.aup.edu/
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        operated_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: AUP
          url: https://www.aup.edu/
  singleuser:
    image:
      name: quay.io/2i2c/2i2c-hubs-image
      tag: "14107b8a85fb"
    memory:
      limit: 8G
      guarantee: 6G
  hub:
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        oauth_callback_url: "https://aup.pilot.2i2c.cloud/hub/oauth_callback"
        allowed_idps:
          http://github.com/login/oauth/authorize:
            username_derivation:
              username_claim: "preferred_username"
      Authenticator:
        # FIXME: In z2jh 3.0.0-beta.1, a truthy allowed_users implies
        #        allow_existing_users=True, while in z3jh 3.0.0 this needs to be
        #        configured explicitly.
        #
        allowed_users: &aup_users
          - swalker
          - shaolintl
        admin_users: *aup_users
